#!/bin/bash

if [ ! -d $HOME/.zsh.d ]; then
	mkdir $HOME/.zsh.d
fi

if [[ -x `which apt` ]]; then
	# Assume this is ubuntu.... Probably will make better later.
	sudo apt install -y zsh fonts-hack git tilix dconf-cli htop curl httpie jq wget
fi

if [ ! -d $HOME/.oh-my-zsh ]; then
	wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O - | KEEP_ZSHRC=yes bash
fi

if [[ -x `which snap` ]]; then
	sudo snap install spotify
	sudo snap install discord
	sudo snap install --classic code
	sudo snap install --classic slack
fi

if [[ -x `which chsh` ]]; then
	sudo chsh -s `which zsh` $USER
fi

if [[ -x `which dconf` ]]; then
	dconf load /com/gexperts/Tilix/ < $HOME/.config/tilix.dconf
	dconf load /org/gnome/desktop/wm/keybindings/ < $HOME/.config/key-bindings.dconf
fi

if [[ -x `which wget` ]]; then
	wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
fi

$HOME/scripts/keepassxc-download
