#!/usr/bin/env bash

brew install jq wget httpie yq homebrew/cask-fonts/font-hack

if [ ! -d $HOME/.oh-my-zsh ]; then
	wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O - | KEEP_ZSHRC=yes bash
fi


