#!/bin/bash

if [ ! -d $HOME/.zsh.d ]; then
	mkdir $HOME/.zsh.d
fi

if [[ -x `which apt` ]]; then
	# Assume this is ubuntu.... Probably will make better later.
	sudo apt install zsh fonts-hack git tilix dconf-cli htop curl
fi

if [ ! -f $HOME/.zsh.d/antigen.zsh ]; then
	curl -L git.io/antigen > $HOME/.zsh.d/antigen.zsh
fi

if [[ -x `which snap` ]]; then
	sudo snap install spotify
	sudo snap install discord 
	sudo snap install --classic code
fi

if [[ -x `which chsh` ]]; then
	sudo chsh -s `which zsh`
fi

if [[ -x `which dconf` ]]; then
	dconf load /com/gexperts/Tilix/ < tilix.dconf
	dconf load /org/gnome/desktop/wm/keybindings/ < .config/key-bindings.dconf
fi
