#!/usr/bin/env bash

TAG=`http https://api.github.com/repos/keepassxreboot/keepassxc/releases/latest | jq -r .tag_name`

wget -O ./keepassxc https://github.com/keepassxreboot/keepassxc/releases/download/$TAG/KeePassXC-$TAG-`uname -i`.AppImage

chmod +x ./keepassxc

sudo mv ./keepassxc /usr/local/bin/
